import { Shipment } from "@/types/shipment";

export const mockShipments: Shipment[] = [
  {
    id: "1",
    trackingNumber: "SHP001",
    status: "in_transit",
    origin: "New York",
    destination: "Los Angeles",
    estimatedDelivery: "2025-02-15",
    lastUpdated: "2025-02-10T14:30:00Z",
    customerName: "John Smith",
    priority: "high",
  },
  {
    id: "2",
    trackingNumber: "SHP002",
    status: "pending",
    origin: "Chicago",
    destination: "Miami",
    estimatedDelivery: "2025-02-16",
    lastUpdated: "2025-02-10T15:00:00Z",
    customerName: "Alice Johnson",
    priority: "medium",
  },
  {
    id: "3",
    trackingNumber: "SHP003",
    status: "delivered",
    origin: "Seattle",
    destination: "Boston",
    estimatedDelivery: "2025-02-14",
    lastUpdated: "2025-02-10T12:00:00Z",
    customerName: "Bob Wilson",
    priority: "low",
  },
  {
    id: "4",
    trackingNumber: "SHP004",
    status: "delayed",
    origin: "San Francisco",
    destination: "Denver",
    estimatedDelivery: "2025-02-17",
    lastUpdated: "2025-02-10T16:45:00Z",
    customerName: "Emma Davis",
    priority: "high",
  },
  {
    id: "5",
    trackingNumber: "SHP005",
    status: "in_transit",
    origin: "Houston",
    destination: "Phoenix",
    estimatedDelivery: "2025-02-15",
    lastUpdated: "2025-02-10T13:15:00Z",
    customerName: "Michael Brown",
    priority: "medium",
  },
  {
    id: "6",
    trackingNumber: "SHP006",
    status: "pending",
    origin: "Atlanta",
    destination: "Dallas",
    estimatedDelivery: "2025-02-18",
    lastUpdated: "2025-02-10T17:30:00Z",
    customerName: "Sophia Martinez",
    priority: "low",
  },
  {
    id: "7",
    trackingNumber: "SHP007",
    status: "delivered",
    origin: "Portland",
    destination: "Las Vegas",
    estimatedDelivery: "2025-02-13",
    lastUpdated: "2025-02-10T11:45:00Z",
    customerName: "William Taylor",
    priority: "medium",
  },
  {
    id: "8",
    trackingNumber: "SHP008",
    status: "in_transit",
    origin: "Austin",
    destination: "San Diego",
    estimatedDelivery: "2025-02-16",
    lastUpdated: "2025-02-10T14:00:00Z",
    customerName: "Olivia Anderson",
    priority: "high",
  },
  {
    id: "9",
    trackingNumber: "SHP009",
    status: "delayed",
    origin: "Nashville",
    destination: "Orlando",
    estimatedDelivery: "2025-02-19",
    lastUpdated: "2025-02-10T18:15:00Z",
    customerName: "James Thomas",
    priority: "medium",
  },
  {
    id: "10",
    trackingNumber: "SHP010",
    status: "pending",
    origin: "Detroit",
    destination: "Philadelphia",
    estimatedDelivery: "2025-02-17",
    lastUpdated: "2025-02-10T16:00:00Z",
    customerName: "Charlotte White",
    priority: "low",
  },
  {
    id: "11",
    trackingNumber: "SHP011",
    status: "in_transit",
    origin: "Minneapolis",
    destination: "Tampa",
    estimatedDelivery: "2025-02-15",
    lastUpdated: "2025-02-10T13:45:00Z",
    customerName: "Benjamin Clark",
    priority: "high",
  },
  {
    id: "12",
    trackingNumber: "SHP012",
    status: "delivered",
    origin: "Raleigh",
    destination: "Salt Lake City",
    estimatedDelivery: "2025-02-14",
    lastUpdated: "2025-02-10T12:30:00Z",
    customerName: "Amelia Rodriguez",
    priority: "medium",
  },
  {
    id: "13",
    trackingNumber: "SHP013",
    status: "delayed",
    origin: "Indianapolis",
    destination: "Kansas City",
    estimatedDelivery: "2025-02-18",
    lastUpdated: "2025-02-10T17:00:00Z",
    customerName: "Mason Lewis",
    priority: "low",
  },
  {
    id: "14",
    trackingNumber: "SHP014",
    status: "pending",
    origin: "Baltimore",
    destination: "Memphis",
    estimatedDelivery: "2025-02-19",
    lastUpdated: "2025-02-10T18:30:00Z",
    customerName: "Evelyn Walker",
    priority: "medium",
  },
  {
    id: "15",
    trackingNumber: "SHP015",
    status: "in_transit",
    origin: "Louisville",
    destination: "Oklahoma City",
    estimatedDelivery: "2025-02-16",
    lastUpdated: "2025-02-10T14:15:00Z",
    customerName: "Elijah Hall",
    priority: "high",
  },
  {
    id: "16",
    trackingNumber: "SHP016",
    status: "delivered",
    origin: "Milwaukee",
    destination: "Albuquerque",
    estimatedDelivery: "2025-02-13",
    lastUpdated: "2025-02-10T11:30:00Z",
    customerName: "Harper Young",
    priority: "low",
  },
  {
    id: "17",
    trackingNumber: "SHP017",
    status: "delayed",
    origin: "Tucson",
    destination: "Fresno",
    estimatedDelivery: "2025-02-20",
    lastUpdated: "2025-02-10T19:00:00Z",
    customerName: "Liam Hernandez",
    priority: "medium",
  },
  {
    id: "18",
    trackingNumber: "SHP018",
    status: "pending",
    origin: "Sacramento",
    destination: "Mesa",
    estimatedDelivery: "2025-02-18",
    lastUpdated: "2025-02-10T17:45:00Z",
    customerName: "Ava King",
    priority: "high",
  },
  {
    id: "19",
    trackingNumber: "SHP019",
    status: "in_transit",
    origin: "Omaha",
    destination: "Colorado Springs",
    estimatedDelivery: "2025-02-15",
    lastUpdated: "2025-02-10T13:00:00Z",
    customerName: "Noah Wright",
    priority: "medium",
  },
  {
    id: "20",
    trackingNumber: "SHP020",
    status: "delivered",
    origin: "Long Beach",
    destination: "Raleigh",
    estimatedDelivery: "2025-02-14",
    lastUpdated: "2025-02-10T12:15:00Z",
    customerName: "Mia Lopez",
    priority: "low",
  },
  {
    id: "21",
    trackingNumber: "SHP021",
    status: "delayed",
    origin: "Oakland",
    destination: "Virginia Beach",
    estimatedDelivery: "2025-02-19",
    lastUpdated: "2025-02-10T18:45:00Z",
    customerName: "Lucas Scott",
    priority: "high",
  },
  {
    id: "22",
    trackingNumber: "SHP022",
    status: "pending",
    origin: "Tulsa",
    destination: "Honolulu",
    estimatedDelivery: "2025-02-20",
    lastUpdated: "2025-02-10T19:30:00Z",
    customerName: "Ella Green",
    priority: "medium",
  },
  {
    id: "23",
    trackingNumber: "SHP023",
    status: "in_transit",
    origin: "Arlington",
    destination: "Anaheim",
    estimatedDelivery: "2025-02-16",
    lastUpdated: "2025-02-10T14:45:00Z",
    customerName: "Alexander Adams",
    priority: "low",
  },
  {
    id: "24",
    trackingNumber: "SHP024",
    status: "delivered",
    origin: "Wichita",
    destination: "Santa Ana",
    estimatedDelivery: "2025-02-13",
    lastUpdated: "2025-02-10T11:15:00Z",
    customerName: "Sofia Nelson",
    priority: "high",
  },
  {
    id: "25",
    trackingNumber: "SHP025",
    status: "delayed",
    origin: "Bakersfield",
    destination: "Riverside",
    estimatedDelivery: "2025-02-20",
    lastUpdated: "2025-02-10T19:15:00Z",
    customerName: "Logan Carter",
    priority: "medium",
  },
];
